// Generated by CoffeeScript 1.3.3
(function() {

  jQuery(function() {
    return jQuery('<iframe id="mygov-bar" src="mygov-bar.html" style="bottom: 0; left: 0; position: fixed; height: 50px; width: 100%; border: none; " />').appendTo('body');
  });

}).call(this);
