// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  jQuery(function() {
    var Notification, Notifications, Tag, Tags;
    Notification = (function(_super) {

      __extends(Notification, _super);

      function Notification() {
        return Notification.__super__.constructor.apply(this, arguments);
      }

      return Notification;

    })(Backbone.Model);
    Notifications = (function(_super) {

      __extends(Notifications, _super);

      function Notifications() {
        return Notifications.__super__.constructor.apply(this, arguments);
      }

      Notifications.prototype.model = Notification;

      return Notifications;

    })(Backbone.Collection);
    Tag = (function(_super) {

      __extends(Tag, _super);

      function Tag() {
        return Tag.__super__.constructor.apply(this, arguments);
      }

      return Tag;

    })(Backbone.Model);
    return Tags = (function(_super) {

      __extends(Tags, _super);

      function Tags() {
        return Tags.__super__.constructor.apply(this, arguments);
      }

      Tags.prototype.model = Tag;

      return Tags;

    })(Backbone.Collection);
  });

}).call(this);
